graphql:
  packages:
    - "com.workshop.graphql.bff"
  sdl:
    enabled: true
spring:
  application:
    name: WS-GRAPHQL-BFF

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

adapter:
  user-service-host: http://${USER_SERVICE_NAME:""}:8080
  api-key: ${API_KEY:""}